# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{supernet}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pat Downey"]
  s.date = %q{2012-12-28}
  s.description = %q{ Supernet is a Ruby library to be used in conjunction with the ipaddress gem
to help manage collections of subnets. }
  s.email = %q{pat.downey@gmail.com}
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "supernet.gemspec",
    "lib/supernet.rb",
    "lib/ext/ipaddress.rb",
    "spec/supernet_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/patdowney/supernet}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.8.24}
  s.summary = %q{IPv4/IPv6 supernet management library}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

